###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  redis:
      database: 0
      host: v.redis1.server
      port: 6379
      timeout: 10000
      password: HuAxIad0e37EE6054667bd9745d5400ecabc
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10000
        min-idle: 100

##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  fund配置  ###################
fund:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 8095

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/moerlong/carloan/**/mapping/*.xml
  typeAliasesPackage: com.moerlong.carloan.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/sportQc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
      username: root
      password: '123456'
      filters: log4j,wall,mergeStat
      
logging:
  level.root: info
  path: logs/
  file: carloan.log

file:
  identity_pic_path: /Users/daiyanchao/local/resources/sport/pics
  identity_pic_url: http://localhost:8888/resource/pics
  identity_pic_urls: http://localhost:8888
  identity_pic_urlsx: /resource/pics
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://140.143.35.16:3306/sportQc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
      username: sportadmin
      password: 'sport2018-C#'
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  path: logs/
  file: carloan.log

file:
  identity_pic_path: /usr/local/resources/sport/pics
  identity_pic_url: http://140.143.35.16/resource/pics
  identity_pic_urls: http://140.143.35.16
  identity_pic_urlsx: /resource/pics
---