###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  redis:
      database: 0
      host: v.redis1.server
      port: 6379
      timeout: 10000
      password: HuAxIad0e37EE6054667bd9745d5400ecabc
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10000
        min-idle: 100

##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  fund配置  ###################
fund:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 8095

car300:
  get_car_brand_list_url: http://v.car300.server:9210/auth/getCarBrandList
  get_car_series_list_url: http://v.car300.server:9210/auth/getCarSeriesList
  get_car_model_list_url: http://v.car300.server:9210/auth/getCarModelList
  get_city_list_url: http://v.car300.server:9210/auth/getCityList
  get_price_url: http://v.car300.server:9210/auth/evalCarPrice
  get_All_City_List: http://724.moerlong.com/carDataService/getAllCityList
  get_All_Brand_List: http://724.moerlong.com/carDataService/getAllBrandList
  get_Car_Series_List: http://724.moerlong.com/carDataService/getCarSeriesList
  get_Car_Model_List: http://724.moerlong.com/carDataService/getCarModelList
  get_car_price: http://724.moerlong.com/carDataService/eval/getUsedCarPriceAnalysis
###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/moerlong/carloan/**/mapping/*.xml
  typeAliasesPackage: com.moerlong.carloan.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/sportQc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
      username: root
      password: '123456'
      filters: log4j,wall,mergeStat
      
logging:
  level.root: info
  path: logs/
  file: carloan.log

file:
  identity_pic_path: /nodedata/node/loantest/identityPic
  liveness_pic_path: /nodedata/node/loantest/livenessPic
  protobuf_path: /nodedata/node/loantest/protobuf
  vehicle_pic_path: /nodedata/node/carInsure/vehiclePic
  register_pic_path: /nodedata/node/carInsure/registerPic
  strong_insure_pic_path: /nodedata/node/carInsure/strongInsurePic
  buss_insure_pic_path: /nodedata/node/carInsure/bussInsurePic
  contact_pdf_path: /nodedata/node/loantest/contactPdf
  #contact_pdf_path: D:/contactPdf
  #mortgage_contract_pic_path: d:/mortgageContract #抵押合同(车管所）照片地址
  #proxy_book_pic_path: d:/proxyBook #委托书（客户签字授权）照片地址
  #cert_photo_pic_path: d:/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  #car_pgs_pic_path: d:/gpsPhoto
  mortgage_contract_pic_path: /nodedata/node/carInsure/mortgageContract #抵押合同(车管所）照片地址
  proxy_book_pic_path: /nodedata/node/carInsure/proxyBook #委托书（客户签字授权）照片地址
  cert_photo_pic_path: /nodedata/node/carInsure/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  car_pgs_pic_path: /nodedata/node/carInsure/gpsPhoto


  identity_pic_url: http://10.1.2.232:8888/resource/loantest/identityPic
  identity_pic_urls: http://10.1.2.232:8888
  identity_pic_urlsx: /resource/loantest/identityPic
  liveness_pic_url: http://static.h2fintech.com/loantest/livenessPic
  protobuf_url: http://static.h2fintech.com/loantest/protobuf
  vehicle_pic_url: http://static.h2fintech.com/carInsure/vehiclePic
  register_pic_url: http://static.h2fintech.com/carInsure/registerPic
  strong_insure_pic_url: http://static.h2fintech.com/carInsure/strongInsurePic
  buss_insure_pic_url: http://static.h2fintech.com/carInsure/bussInsurePic

  
system:
  paycenter:
    channleKey: HFadface123@12#as
    costUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/easyDeduceRequestService
    costQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryCostOrder
    payUrl: http://v.paycenter.server:9781/paycenter/services/borrow/mrlFrontPayRequestService
    payQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryPayOrder
    singleCostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/borrowDeduceRequestService
    singlePayQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/mrlBorrowPayRequestService
    mrlcostUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/morReplaceCostRequestService
    mrlcostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/morQueryRequestService
  sms:
    url: http://v.ismg.server:9000/ismg/sms/
  selectBank:
    url: http://v.paycenter.server:9781/paycenter/services/getBankInfoRequestService
  excel:
    filepath: /data/fund_sys/
  telecomAuth:
      url: http://123.59.181.202:9990/api/v1/report/car_loan/support/carrier
---

##########################################################
###################  测试（开发）环境的profile  ###################
##########################################################
spring:
  profiles: test
  datasource:
      url: jdbc:mysql://v1.mysql.server:3306/carloanfront?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
      username: car_loan_sa
      password: '@tsingnuo2017-C#'
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  path: logs/
  file: carloan.log

file:
  identity_pic_path: /nodedata/node/loantest/identityPic
  liveness_pic_path: /nodedata/node/loantest/livenessPic
  protobuf_path: /nodedata/node/loantest/protobuf
  vehicle_pic_path: /nodedata/node/carInsure/vehiclePic
  register_pic_path: /nodedata/node/carInsure/registerPic
  strong_insure_pic_path: /nodedata/node/carInsure/strongInsurePic
  buss_insure_pic_path: /nodedata/node/carInsure/bussInsurePic
  contact_pdf_path: /nodedata/node/loantest/contactPdf
  #contact_pdf_path: D:/contactPdf
  #mortgage_contract_pic_path: d:/mortgageContract #抵押合同(车管所）照片地址
  #proxy_book_pic_path: d:/proxyBook #委托书（客户签字授权）照片地址
  #cert_photo_pic_path: d:/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  #car_pgs_pic_path: d:/gpsPhoto
  mortgage_contract_pic_path: /nodedata/node/carInsure/mortgageContract #抵押合同(车管所）照片地址
  proxy_book_pic_path: /nodedata/node/carInsure/proxyBook #委托书（客户签字授权）照片地址
  cert_photo_pic_path: /nodedata/node/carInsure/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  car_pgs_pic_path: /nodedata/node/carInsure/gpsPhoto


  identity_pic_url: http://10.1.2.239:8888/resource/loantest/identityPic
  identity_pic_urls: http://10.1.2.239:8888
  identity_pic_urlsx: /resource/loantest/identityPic
  liveness_pic_url: http://static.h2fintech.com/loantest/livenessPic
  protobuf_url: http://static.h2fintech.com/loantest/protobuf
  vehicle_pic_url: http://static.h2fintech.com/carInsure/vehiclePic
  register_pic_url: http://static.h2fintech.com/carInsure/registerPic
  strong_insure_pic_url: http://static.h2fintech.com/carInsure/strongInsurePic
  buss_insure_pic_url: http://static.h2fintech.com/carInsure/bussInsurePic


system:
  paycenter:
    channleKey: HFadface123@12#as
    costUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/easyDeduceRequestService
    costQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryCostOrder
    payUrl: http://v.paycenter.server:9781/paycenter/services/borrow/mrlFrontPayRequestService
    payQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryPayOrder
    singleCostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/borrowDeduceRequestService
    singlePayQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/mrlBorrowPayRequestService
    mrlcostUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/morReplaceCostRequestService
    mrlcostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/morQueryRequestService
  sms:
    url: http://v.ismg.server:9000/ismg/sms/
  selectBank:
    url: http://v.paycenter.server:9781/paycenter/services/getBankInfoRequestService
  excel:
    filepath: /data/fund_sys/
  telecomAuth:
      url: http://123.59.181.202:9990/api/v1/report/car_loan/support/carrier
---

##########################################################
###################  UAT测试环境的profile  ###################
##########################################################
spring:
  profiles: uat
  datasource:
      url: jdbc:mysql://v1.mysql.server:3306/carloanuat?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
      username: car_loan_sa
      password: '@tsingnuo2017-C#'
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  path: logs/
  file: carloan.log

file:
  identity_pic_path: /nodedata/node/loantest/identityPic
  liveness_pic_path: /nodedata/node/loantest/livenessPic
  protobuf_path: /nodedata/node/loantest/protobuf
  vehicle_pic_path: /nodedata/node/carInsure/vehiclePic
  register_pic_path: /nodedata/node/carInsure/registerPic
  strong_insure_pic_path: /nodedata/node/carInsure/strongInsurePic
  buss_insure_pic_path: /nodedata/node/carInsure/bussInsurePic
  contact_pdf_path: /nodedata/node/loantest/contactPdf
  #contact_pdf_path: D:/contactPdf
  #mortgage_contract_pic_path: d:/mortgageContract #抵押合同(车管所）照片地址
  #proxy_book_pic_path: d:/proxyBook #委托书（客户签字授权）照片地址
  #cert_photo_pic_path: d:/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  #car_pgs_pic_path: d:/gpsPhoto
  mortgage_contract_pic_path: /nodedata/node/carInsure/mortgageContract #抵押合同(车管所）照片地址
  proxy_book_pic_path: /nodedata/node/carInsure/proxyBook #委托书（客户签字授权）照片地址
  cert_photo_pic_path: /nodedata/node/carInsure/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  car_pgs_pic_path: /nodedata/node/carInsure/gpsPhoto


  identity_pic_url: http://10.1.2.247:8096/identityPic
  identity_pic_urls: http://10.1.2.247:8096
  identity_pic_urlsx: /identityPic
  liveness_pic_url: http://static.h2fintech.com/loantest/livenessPic
  protobuf_url: http://static.h2fintech.com/loantest/protobuf
  vehicle_pic_url: http://static.h2fintech.com/carInsure/vehiclePic
  register_pic_url: http://static.h2fintech.com/carInsure/registerPic
  strong_insure_pic_url: http://static.h2fintech.com/carInsure/strongInsurePic
  buss_insure_pic_url: http://static.h2fintech.com/carInsure/bussInsurePic


system:
  paycenter:
    channleKey: HFadface123@12#as
    costUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/easyDeduceRequestService
    costQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryCostOrder
    payUrl: http://v.paycenter.server:9781/paycenter/services/borrow/mrlFrontPayRequestService
    payQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryPayOrder
    singleCostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/borrowDeduceRequestService
    singlePayQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/mrlBorrowPayRequestService
    mrlcostUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/morReplaceCostRequestService
    mrlcostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/morQueryRequestService
  sms:
    url: http://v.ismg.server:9000/ismg/sms/
  selectBank:
    url: http://v.paycenter.server:9781/paycenter/services/getBankInfoRequestService
  excel:
    filepath: /data/fund_sys/
  telecomAuth:
      url: http://123.59.181.202:9990/api/v1/report/car_loan/support/carrier
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://v1.mysql.server:3306/carloanfront?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&multiStatementAllow=true
      username: car_loan_sa
      password: '@tsingnuo2017-C#'
      filters: log4j,wall,mergeStat
logging:
  level.root: info
  path: logs/
  file: carloan.log
file:
  identity_pic_path: /nodedata/node/loantest/identityPic
  liveness_pic_path: /nodedata/node/loantest/livenessPic
  protobuf_path: /nodedata/node/loantest/protobuf
  vehicle_pic_path: /nodedata/node/carInsure/vehiclePic
  register_pic_path: /nodedata/node/carInsure/registerPic
  strong_insure_pic_path: /nodedata/node/carInsure/strongInsurePic
  buss_insure_pic_path: /nodedata/node/carInsure/bussInsurePic
  contact_pdf_path: /nodedata/node/loantest/contactPdf
  #contact_pdf_path: D:/contactPdf
  #mortgage_contract_pic_path: d:/mortgageContract #抵押合同(车管所）照片地址
  #proxy_book_pic_path: d:/proxyBook #委托书（客户签字授权）照片地址
  #cert_photo_pic_path: d:/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  #car_pgs_pic_path: d:/gpsPhoto
  mortgage_contract_pic_path: /nodedata/node/carInsure/mortgageContract #抵押合同(车管所）照片地址
  proxy_book_pic_path: /nodedata/node/carInsure/proxyBook #委托书（客户签字授权）照片地址
  cert_photo_pic_path: /nodedata/node/carInsure/certPhoto #身份证复印件照片地址(上有客户签名和手机号码)
  car_pgs_pic_path: /nodedata/node/carInsure/gpsPhoto

  #图片服务器地址
  identity_pic_url: http://car.moerlong.com/loantest/identityPic
  identity_pic_urls: http://car.moerlong.com
  identity_pic_urlsx: /loantest/identityPic
  liveness_pic_url: http://static.h2fintech.com/loantest/livenessPic
  protobuf_url: http://static.h2fintech.com/loantest/protobuf
  vehicle_pic_url: http://static.h2fintech.com/carInsure/vehiclePic
  register_pic_url: http://static.h2fintech.com/carInsure/registerPic
  strong_insure_pic_url: http://static.h2fintech.com/carInsure/strongInsurePic
  buss_insure_pic_url: http://static.h2fintech.com/carInsure/bussInsurePic


system:
  paycenter:
    channleKey: HFadface123@12#as
    costUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/easyDeduceRequestService
    costQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryCostOrder
    payUrl: http://v.paycenter.server:9781/paycenter/services/borrow/mrlFrontPayRequestService
    payQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/queryPayOrder
    singleCostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/borrowDeduceRequestService
    singlePayQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/mrlBorrowPayRequestService
    mrlcostUrl: http://v.paycenter.server:9781/paycenter/services/borrow/replaceCost/morReplaceCostRequestService
    mrlcostQueryUrl: http://v.paycenter.server:9781/paycenter/services/query/replaceCost/morQueryRequestService
  sms:
    url: http://v.ismg.server:9000/ismg/sms/
  selectBank:
    url: http://v.paycenter.server:9781/paycenter/services/getBankInfoRequestService
  excel:
    filepath: /data/fund_sys/
  telecomAuth:
      url: http://123.59.181.202:9990/api/v1/report/car_loan/support/carrier
---


